---
title: "First Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(babynames)
library(dygraphs)
library(highcharter)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
lungDeaths <- cbind(mdeaths, fdeaths)
dygraph(lungDeaths) %>%
  dySeries("mdeaths", label = "Male") %>%
  dySeries("fdeaths", label = "Female") %>%
  dyOptions(stackedGraph = TRUE) %>%
  dyRangeSelector(height = 20)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
df = babynames %>%
  filter(grepl("^I", name)) %>%
  group_by(name) %>%
  tally(wt=n) %>%
  arrange(desc(n)) %>%
  slice(1:4)
  
highchart() %>%
  hc_chart(type = "column") %>%
  hc_title(text = "Test") %>%
  hc_xAxis(categories = as.list(df[["name"]])) %>%
  hc_plotOptions(column = list(dataLabels = list(enabled = TRUE))) %>%
  hc_add_series(name = "Irene", data = df[["n"]][which(df[["name"]] == "Irene")]) %>%
  hc_add_series(name = "Isabella", data = df[["n"]][which(df[["name"]] == "Isabella")]) %>%
  hc_add_series(name = "Isaac", data = df[["n"]][which(df[["name"]] == "Isaac")]) %>%
  hc_add_series(name = "Ian", data = df[["n"]][which(df[["name"]] == "Ian")])
```

### Chart C

```{r}
plot(iris)
```